In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

In [50]:
data = load_diabetes()

In [51]:
x = data.data
y = data.target

In [52]:
x.shape,y.shape

((442, 10), (442,))

In [12]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [13]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [14]:
from sklearn.model_selection import train_test_split

In [53]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lr = LinearRegression()

In [18]:
lr.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred = lr.predict(x_test)

In [20]:
from sklearn.metrics import r2_score

In [21]:
r2_score(y_test,y_pred)

0.573193570593531

In [22]:
lr.coef_

array([ -10.33295431, -200.32092838,  480.38539241,  330.28218965,
       -703.09114414,  426.31375515,   91.9877493 ,  179.45602594,
        736.08635332,   27.34600212])

In [23]:
lr.intercept_

150.07159328451039

In [63]:
class MultipleLinear:
    def __init__(self):
        self.weigts = 0
        self.bias = 0
        self.betas = 0
    def fit(self,x_train,y_train):
        x_train = np.insert(x_train,0,1,axis=1)
        #weights
        self.betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
        self.bias = self.betas[0]
        self.weights = self.betas[1:]
    def predict(self,x_test):
        x_test = np.insert(x_test,0,1,axis=1)
        y_pred = np.dot(x_test,self.betas)
        return y_pred

In [64]:
ler = MultipleLinear()

In [65]:
ler.fit(x_train,y_train)

In [46]:
x_test.shape

(89, 10)

In [66]:
y_pred = ler.predict(x_test)

In [68]:
r2_score(y_test,y_pred)

0.5182175923061774